import React from "react";
import Head from "next/head";
import styles from '../styles/Home.module.css'

export default function About() {
  console.log("in About");

  // fs.readdirSync(__dirname);

  return (
    <div className={styles.container}>
      <Head>
        <title>About Next App</title>
        <meta name="description" content="Generated by Strohm" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>About</h1>
        <div className={styles.description}>This is the about page</div>
      </main>
    </div>
  );
}
