import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import * as fs from "fs";

class AboutData {
  text: string = "";
  files: string[] = [];

  public serialize(): string {
    return JSON.stringify(this);
  }

  public static fromString(dataString: string): AboutData{
    let dataObject: AboutData = JSON.parse(dataString);

    return dataObject;
  }
}

interface MyProps {
  data: string;
}

export default class About extends React.Component<MyProps> {
  render() {
    console.log("in About");

    let data: AboutData = AboutData.fromString(this.props.data);
    let listItems: any = data.files.map((d) => <li key={d}>{d}</li>);

    return (
      <div className={styles.container}>
        <Head>
          <title>About Next App</title>
          <meta name="description" content="Generated by Strohm" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>About</h1>
          <div className={styles.description}>This is the about page</div>
          <h2>Text:</h2>
          <div>{data.text}</div>
          <h2>Files:</h2>
          <div>
            <ul>
              {listItems}
            </ul>
          </div>
        </main>
      </div>
    );
  }
}

// This gets called on every request
export async function getServerSideProps () {
  console.log("in getServerSideProps");
  let files: string[] = fs.readdirSync("./");

  let aboutData: AboutData = new AboutData();
  aboutData.text = "Hi Strohm!";
  aboutData.files = files;

  let data: string = aboutData.serialize();

  // Pass data to the page via props
  return {
    props: { data }
  };
}
